\documentclass[a4paper]{article}

\title{Documentation of the R package epiphylo}
\author{Xavier Didelot}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

<<echo=FALSE>>=
library('epiphylo')
set.seed(1)
@

A pathogen has an effective within-host population size of $N_e=100$ and a generation time $g=1$ day, so that $N_e g=100/365$ years. The basic reproduction number is $R=1$. To following command simulates an outbreak of this pathogen: 
<<>>=
simu <- simulateOutbreak(R=1,neg=100/365)
@

This simulation contains both the transmission tree between infected hosts and the within-host phlogenetic tree of each host. This can be visualised as a colored phlogenetic tree, where each host is represented by a unique color:

\begin{center}
<<fig=TRUE>>=
plotBothTree(simu)
@
\end{center}

The phylogenetic tree can be extracted and converted into a phylo object from the ape package:

<<fig=TRUE>>=
library(ape)
ptree<-ptreeFromFullTree(simu)
p<-phyloFromPtree(ptree)
plot(p)
@

The transmission tree can be extract and plotted separately from the phylogeny:

<<fig=TRUE>>=
ttree<-ttreeFromFullTree(simu)
plotTTree(ttree)
@

\end{document}