\documentclass[a4paper]{article}
\usepackage{geometry}
\geometry{tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}

\title{Documentation of the R package TransPhylo}
\author{Xavier Didelot}

\begin{document}

%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Using TransPhylo}

<<include=FALSE>>=
library(knitr)
opts_chunk$set(fig.width=5,fig.height=5,out.width="4in",out.height="4in",fig.align = "center")
@

\maketitle

<<include=FALSE>>=
library('TransPhylo')
set.seed(0)
@

\section{Simulation}

A pathogen has an effective within-host population size of $N_e=100$ and a generation time $g=1$ day, so that $N_e g=100/365$ years. The offspring distribution is negative binomial with parameters (5,0.5) so that basic reproduction number is $R=5$. The generation time is Gamma distributed with parameters (10,0.1). The probability is sampling an 'old' individual is $\pi=0.25$. The following commands specify these parameters:
<<>>=
neg=100/365
off.r=5
off.p=0.5
w.shape=10
w.scale=0.1
pi=0.25
@

We simulate an outbreak that starts in 2005 and which and is observed up to 2010:

<<>>=
simu <- simulateOutbreak(neg=neg,pi=pi,off.r=off.r,off.p=off.p,w.shape=w.shape,
                         w.scale=w.scale,dateStartOutbreak=2005,datePresent=2008)
@

This simulation contains both the transmission tree between infected hosts and the within-host phlogenetic tree of each host. This can be visualised as a colored phlogenetic tree, where each host is represented by a unique color:

\begin{center}
<<>>=
plotBothTree(simu,showLabels=F)
@
\end{center}

The transmission tree can be extracted and plotted separately from the phylogeny:

<<>>=
ttree<-ttreeFromFullTree(simu)
plotTTree(ttree,w.shape,w.scale,showLabels=F)
@

The phylogenetic tree can be extracted and converted into a phylo object from the ape package:

<<>>=
library(ape)
ptree<-ptreeFromFullTree(simu)
p<-phyloFromPtree(ptree)
plot(p,show.tip.label=F)
@

\section{Inference of transmission tree given a phylogeny}

A phylo object can be turned into a phylogenetic tree and complemented with a wild guess at the transmission tree in order to provide the starting point of the MCMC procedure:

<<>>=
ptree<-ptreeFromPhylo(p,dateLastSample=max(simu[,1]))
full<-makeFullTreeFromPTree(ptree)
plotBothTree(full,showLabels=F)
@

The MCMC procedure to infer the transmission tree given the phylogenetic tree can be run as follows:

<<message=FALSE>>=
record<-inferTTree(ptree,mcmcIterations=100,w.shape=w.shape,w.scale=w.scale,
                   startNeg=neg,startPi=0.5,startOff.p=off.p,startOff.r=1,
                   updateOff.r=T,updatePi=T,updateNeg=T,updateOff.p=F,datePresent=2008)
@

This returns a record of all MCMC iterations. This is what the transmission tree looks like at the end of the MCMC:

<<>>=
lastIteration<-record[[length(record)]]
plotBothTree(lastIteration$tree,showLabels=F)
@

Traces of the MCMC:

<<echo=FALSE>>=
par(mfrow=c(2,2))
plot(sapply(record,function(x) x$pTTree+x$pPTree),ylab='Posterior probability',xlab='MCMC iterations',type='l')
plot(sapply(record,function(x) x$pi),ylab='Sampling proportion pi',xlab='MCMC iterations',type='l')
plot(sapply(record,function(x) x$neg),ylab='Within-host coalescent rate Ne*g',xlab='MCMC iterations',type='l')
plot(sapply(record,function(x) x$off.r*(1-x$off.p)/x$off.p),ylab='Basic reproduction number R',xlab='MCMC iterations',type='l')
@

\end{document}
