\documentclass[a4paper]{article}

%\VignetteIndexEntry{UsingTransPhylo}
%\VignetteEngine{knitr::knitr}

\usepackage{geometry}
\geometry{tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}

\title{Vignette introducing the R package TransPhylo}
\author{Xavier Didelot}

\begin{document}

<<include=FALSE>>=
library(knitr)
opts_chunk$set(fig.width=5,fig.height=5,out.width="4in",out.height="4in",fig.align = "center")
@

\maketitle

<<include=FALSE>>=
library('TransPhylo')
set.seed(0)
@

\section{Simulation}

In this first part we will simulate a dataset for use in the second part. If you already have a dataset on which you want to apply TransPhylo you can skip this part, although you might still find it useful to read as it introduces some of the concepts in our model.

A pathogen has an effective within-host population size of $N_e=100$ and a generation time $g=1$ day, so that $N_e g=100/365$ year. The offspring distribution is negative binomial with mean equal to the basic reproduction number $R=5$. Both the generation time and the sampling time are Gamma distributed with parameters (10,0.1) which has a mean of 1 year. The density of sampling is $\pi=0.25$. The following commands specify these parameters:
<<>>=
neg=100/365
off.r=5
w.shape=10
w.scale=0.1
pi=0.25
@

We simulate an outbreak that starts in 2005 and which and is observed up to 2008:

<<>>=
simu <- simulateOutbreak(neg=neg,pi=pi,off.r=off.r,w.shape=w.shape,
                         w.scale=w.scale,dateStartOutbreak=2005,dateT=2008)
@

This simulation contains both the transmission tree between infected hosts and the within-host phylogenetic tree of each host. This can be visualised as a colored phlogenetic tree, where each host is represented by a unique color:

\begin{center}
<<>>=
plotBothTree(simu)
@
\end{center}

The transmission tree can be extracted and plotted separately from the phylogeny:

<<>>=
ttree<-ttreeFromFullTree(simu)
plotTTree(ttree,w.shape,w.scale)
@

The phylogenetic tree can be extracted and converted into a phylo object from the ape package:

<<>>=
library(ape)
ptree<-ptreeFromFullTree(simu)
p<-phyloFromPtree(ptree)
plot(p)
axisPhylo()
@

Let us save this tree into a Newick file so that we can use it as input in the second part.

<<>>=
write.tree(p,'tree.nwk',append = F)
@


Note that this phylogeny is scaled in years, but time is measured only relatively to the 
date of the last sample which is at 0 on the x-axis of the figure above. To use this tree
in the second part we also need to know exactly when was the last sample taken:

<<>>=
dls=max(simu[,1])
print(dls)
@

\section{Inference of transmission tree given a phylogeny}

This second part is independent from the first part, so we start by erasing the workspace except for the parameters \verb+w.shape+ and \verb+w.scale+ that specify the generation and sampling distributions, and the date \verb+dls+ at which the last sample was taken (see above): 

<<>>=
rm(list=setdiff(ls(),c('w.shape','w.scale','dls')))
@

Our starting point is a timed phylogenetic tree such as the one created in the previous part.
Because such a phylogeny is timed relatively and not absolutely, we also need to indicate when the
last sample was taken, which in the simulation above was stored as \verb+dls+:

<<hide-par,echo=1,results='hide'>>=
ptree<-ptreeFromPhylo(read.tree('tree.nwk'),dateLastSample=dls)
file.remove('tree.nwk') #Erase the tree.nwk file since we will not need it anymore
@

The MCMC procedure to infer the transmission tree given the phylogenetic tree can be run as follows:

<<message=FALSE>>=
record<-inferTTree(ptree,mcmcIterations=100,w.shape=w.shape,w.scale=w.scale,
                   startNeg=1,startPi=0.5,startOff.r=1,
                   updateOff.r=T,updatePi=T,updateNeg=T,dateT=2008)
@

This returns a record of all MCMC iterations. This is what the transmission tree looks like at the end of the MCMC:

<<>>=
lastIteration<-record[[length(record)]]
plotBothTree(lastIteration$tree)
@

Traces of the MCMC can be plotted as follows:

<<>>=
par(mfrow=c(2,2))
plot(sapply(record,function(x) x$pTTree+x$pPTree),ylab='Posterior probability',
     xlab='MCMC iterations',type='l')
plot(sapply(record,function(x) x$pi),ylab='Sampling proportion pi',
     xlab='MCMC iterations',type='l')
plot(sapply(record,function(x) x$neg),ylab='Within-host coalescent rate Ne*g',
     xlab='MCMC iterations',type='l')
plot(sapply(record,function(x) x$off.r),ylab='Basic reproduction number R',
     xlab='MCMC iterations',type='l')
@

A consensus transmission tree can be built as follows:
<<>>=
cons=consTTree(record)
plotTTree(cons,w.shape,w.scale)
@

\end{document}
