\documentclass[a4paper]{article}

\title{Documentation of the R package epiphylo}
\author{Xavier Didelot}

\begin{document}
\SweaveOpts{concordance=TRUE}
%\VignetteIndexEntry{Using epiphylo}

\maketitle

<<echo=FALSE>>=
library('epiphylo')
set.seed(1)
@

\section{Simulation}

A pathogen has an effective within-host population size of $N_e=100$ and a generation time $g=1$ day, so that $N_e g=100/365$ years. The basic reproduction number is $R=1$. To following command simulates an outbreak of this pathogen: 
<<>>=
simu <- simulateOutbreak(R=1,neg=100/365)
@

This simulation contains both the transmission tree between infected hosts and the within-host phlogenetic tree of each host. This can be visualised as a colored phlogenetic tree, where each host is represented by a unique color:

\begin{center}
<<fig=TRUE>>=
plotBothTree(simu)
@
\end{center}

The transmission tree can be extracted and plotted separately from the phylogeny:

<<fig=TRUE>>=
ttree<-ttreeFromFullTree(simu)
plotTTree(ttree)
@

The phylogenetic tree can be extracted and converted into a phylo object from the ape package:

<<fig=TRUE>>=
library(ape)
ptree<-ptreeFromFullTree(simu)
p<-phyloFromPtree(ptree)
plot(p)
@

\section{Inference of transmission tree given a phylogeny}

A phylo object can be turned  into a phylogenetic tree and complemented with a wild guess at the transmission tree in order to provide the starting point of the MCMC procedure:

<<fig=TRUE>>=
ptree<-ptreeFromPhylo(p)
full<-makeFullTreeFromPTree(ptree)
plotBothTree(full)
@

The MCMC procedure to infer the transmission tree given the phylogenetic tree can be run as follows:

<<results=hide>>=
record<-inferTTree(ptree,mcmcIterations=100)
@

This returns a record of all MCMC iterations. Let's see what the transmission tree looked like at the end of the MCMC:

<<fig=TRUE>>=
lastIteration<-record[[length(record)]]
plotBothTree(lastIteration$tree)
@

\end{document}