\documentclass[a4paper]{article}

\title{Documentation of the R package epiphylo}
\author{Xavier Didelot}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

<<echo=FALSE>>=
library('epiphylo')
set.seed(1)
@

A pathogen has an effective within-host population size of $N_e=100$ and a generation time $g=1$ day, so that the within-host coalescent rate is $N_e g=100/365$ years. The basic reproduction number is $R=1$. To following command simulates an outbreak of this pathogen: 
<<>>=
simu <- simulateOutbreak(R=1,neg=100/365)
@

This simulation contains both the transmission tree between infected hosts and the within-host phlogenetic tree of each host. This can be visualised as a colored phlogenetic tree, where each host is represented by a unique color:

\begin{center}
<<fig=TRUE>>=
plotBothTree(simu)
@
\end{center}



\end{document}